export const PLANS = [
  {
    tier: "FREE",
    name: "Free",
    price: "£0",
    period: "forever",
    description: "Try NovaCRM with no commitment.",
    features: ["1 CRM", "Limited records", "NovaCRM branding", "Basic features"],
    cta: "Start for free",
    href: "/register",
    highlighted: false,
  },
  {
    tier: "STARTER",
    name: "Starter",
    price: "£19",
    period: "/month",
    description: "For freelancers and small teams.",
    features: [
      "14-day free trial",
      "Unlimited records",
      "Remove branding",
      "Basic automations",
      "Email support",
    ],
    cta: "Start with Starter",
    href: "/register?plan=starter",
    highlighted: false,
  },
  {
    tier: "PRO",
    name: "Pro",
    price: "£49",
    period: "/month",
    description: "For growing service businesses.",
    features: [
      "14-day free trial",
      "Multiple CRMs",
      "Advanced automations",
      "Team collaboration",
      "API access",
      "Integrations",
    ],
    cta: "Start with Pro",
    href: "/register?plan=pro",
    highlighted: true,
  },
  {
    tier: "BUSINESS",
    name: "Business",
    price: "£99",
    period: "/month",
    description: "For teams that need control at scale.",
    features: [
      "14-day free trial",
      "Unlimited users",
      "Advanced permissions",
      "White label",
      "Priority support",
      "Advanced analytics",
    ],
    cta: "Start with Business",
    href: "/register?plan=business",
    highlighted: false,
  },
] as const;

export type PlanTierKey = (typeof PLANS)[number]["tier"];
