export const PLANS = [
  {
    tier: "FREE",
    name: "Free",
    price: "£0",
    period: "forever",
    description: "Try NovaCRM with no commitment.",
    features: ["1 CRM", "Limited records", "NovaCRM branding", "Basic features"],
    cta: "Start for free",
    href: "/register",
    highlighted: false,
  },
  {
    tier: "STARTER",
    name: "Starter",
    price: "£19",
    period: "/month",
    description: "For freelancers and small teams.",
    features: [
      "14-day free trial",
      "Multiple CRMs",
      "Unlimited records",
      "Remove branding",
      "Automations",
      "Email support",
    ],
    cta: "Start with Starter",
    href: "/register?plan=starter",
    highlighted: false,
  },
  {
    tier: "PRO",
    name: "Pro",
    price: "£49",
    period: "/month",
    description: "For growing service businesses.",
    features: ["14-day free trial", "Everything in Starter", "Integrations & webhooks"],
    cta: "Start with Pro",
    href: "/register?plan=pro",
    highlighted: true,
  },
  {
    tier: "BUSINESS",
    name: "Business",
    price: "£99",
    period: "/month",
    description: "For teams that need more hands-on help.",
    features: [
      "14-day free trial",
      "Everything in Pro",
      "Dedicated onboarding call",
      "Custom setup support",
    ],
    cta: "Start with Business",
    href: "/register?plan=business",
    highlighted: false,
  },
] as const;

export type PlanTierKey = (typeof PLANS)[number]["tier"];
